language: C++

dist: xenial

script:
  - make
  - ./bin/test
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code
